/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gelabert.ytdlgui;

import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.nio.file.Files;

/**
 *
 * @author jordi.gelabert
 */
public class MediaLibraryPanel extends javax.swing.JPanel {

    private List<MediaFile> allFiles = new ArrayList<>();
    private MediaTableModel tableModel;
    private MainFrame mainFrame;

    
    /**
     * Creates new form MediaLibraryPanel
     */
    public MediaLibraryPanel() {
        initComponents();
         loadFilesFromFolder();
    }
    
    
    public MediaLibraryPanel(MainFrame mainFrame) {
        this();                // crida al constructor que inicialitza components
        this.mainFrame = mainFrame;
    }
    
    private void loadFilesFromFolder() {
    File folder = new File(System.getProperty("user.home"), "Downloads");
    //File folder = new File("C:/Users/jordi.gelabert/Downloads");

    allFiles.clear();

    File[] files = folder.listFiles();
    if (files == null) {
        return;
    }

    for (File f : files) {
        if (f.isFile()) {
            String mime = "application/octet-stream";
            try {
                String detected = Files.probeContentType(f.toPath());

                if (detected != null) {
                    mime = detected;
                }
            } catch (IOException ex) {
                // si falla, deixem el mime per defecte
            }

            long size = f.length();

            MediaFile mf = new MediaFile(
                f.getName(),
                size,
                mime,
                LocalDateTime.now(),
                f.getAbsolutePath()
            );

            allFiles.add(mf);
        }
    }

    // 🔹 Actualitzar la JList
    lstMedia.setListData(
    allFiles.stream()
            .map(MediaFile::getName)
            .toArray(String[]::new)
);


    // 🔹 Assignar model a JTable
    tableModel = new MediaTableModel(allFiles);
    tblMedia.setModel(tableModel);

    lblCountElements.setText(allFiles.size() + " elementos");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMedia = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedia = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        lblCountElements = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 400));

        jLabelTittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTittle.setText("Media Library");

        lblType.setText("Type:");

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Audio", "Video", "Other" }));

        lstMedia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstMedia);

        tblMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMedia);

        btnDelete.setText("Delete Selected");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back to main");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSearch.setText("Search:");

        lblCountElements.setText("0 elements");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTittle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCountElements)
                                .addGap(49, 49, 49)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSearch))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTittle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearch)
                            .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblType))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblCountElements)
                    .addComponent(btnDelete))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int index = lstMedia.getSelectedIndex();
    if (index == -1) {
        return; // res seleccionat
    }

    // MediaFile corresponent a la posició seleccionada
    MediaFile selected = allFiles.get(index);

    File f = new File(selected.getPath());
    f.delete(); // simulació senzilla: no comprovam errors

    // Treure'l de la llista interna
    allFiles.remove(index);

    // Actualitzar JList
    lstMedia.setListData(
        allFiles.stream()
                .map(MediaFile::getName)
                .toArray(String[]::new)
    );

    // Actualitzar JTable
    tableModel = new MediaTableModel(allFiles);
    tblMedia.setModel(tableModel);

    // Comptador
    lblCountElements.setText(allFiles.size() + " elementos");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
            if (mainFrame != null) {
        mainFrame.showCard("MAIN");
    }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JLabel lblCountElements;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblType;
    private javax.swing.JList<String> lstMedia;
    private javax.swing.JTable tblMedia;
    // End of variables declaration//GEN-END:variables
}
