/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gelabert.ytdlgui;

/**
 *
 * @author JGR
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    private String authToken; 
    // 🔹 Backend client
    
    // 🔹 Panells de l'aplicació
    private LoginPanel loginPanel;
    private MainPanel mainPanel;
    private PreferencesPanel prefsPanel;
    private MediaLibraryPanel mediaLibraryPanel;
    private MediaPollingComponent pollingComponent;



    /**
     * Creates new form MainFrame
     */
public MainFrame() {
    initComponents();

    // 🔹 Menús desactivats al principi
    setLoggedIn(false);

    // ❗ ELIMINAT — NO ES POT FER SERVIR ApiClient DIRECTAMENT
    // apiClient = new ApiClient("https://dimedianetapi9.azurewebsites.net");

    // 🔹 Crear component de polling (substitut oficial de ApiClient)
    pollingComponent = new MediaPollingComponent();
    pollingComponent.setApiUrl("https://dimedianetapi9.azurewebsites.net");
    pollingComponent.setPollingIntervalSeconds(10);
    pollingComponent.setRunning(false); // aturat fins login

    // Listener quan hi ha media nou (opcional)
    pollingComponent.addMediaPollingListener(evt -> {
        System.out.println(">>> " + evt.getNewMedia().size() +
            " fitxers nous a les " + evt.getDiscoveredAt());
    });

    // 🔹 Crear panells usant el COMPONENT (no ApiClient)
    loginPanel = new LoginPanel(this, pollingComponent);
    mainPanel = new MainPanel();              // si el necessites, li passam el component més tard
    prefsPanel = new PreferencesPanel(this);
    mediaLibraryPanel = new MediaLibraryPanel(this);

    // 🔹 Afegir panells al CardLayout
    contentPanel.add(loginPanel, "LOGIN");
    contentPanel.add(mainPanel, "MAIN");
    contentPanel.add(prefsPanel, "PREFS");
    contentPanel.add(mediaLibraryPanel, "LIBRARY");

    // 🔹 Remember Me
    String[] remembered = RememberHelper.load();
    if (remembered != null) {
        loginPanel.setEmail(remembered[0]);
        loginPanel.setRememberMe(true);
    }

    // 🔹 Primera pantalla
    showCard("LOGIN");

    pack();
    setLocationRelativeTo(null);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        menuPreferences = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        menuViewDownloader = new javax.swing.JMenuItem();
        menuViewLibrary = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ytdlgui");
        setPreferredSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        contentPanel.setPreferredSize(new java.awt.Dimension(600, 300));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        File.setText("File");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        File.add(menuExit);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        File.add(menuLogout);

        jMenuBar1.add(File);

        Edit.setText("Edit");

        menuPreferences.setText("Preferences");
        menuPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPreferencesActionPerformed(evt);
            }
        });
        Edit.add(menuPreferences);

        jMenuBar1.add(Edit);

        View.setText("View");

        menuViewDownloader.setText("Downloader");
        menuViewDownloader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewDownloaderActionPerformed(evt);
            }
        });
        View.add(menuViewDownloader);

        menuViewLibrary.setText("Library");
        menuViewLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewLibraryActionPerformed(evt);
            }
        });
        View.add(menuViewLibrary);

        jMenuBar1.add(View);

        Help.setText("Help");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        Help.add(menuAbout);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_menuExitActionPerformed

    private void menuPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPreferencesActionPerformed
        // TODO add your handling code here:
        showCard("PREFS");
    }//GEN-LAST:event_menuPreferencesActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
         AboutDialog dialog = new AboutDialog(this, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuViewDownloaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewDownloaderActionPerformed
        // TODO add your handling code here:
        showCard("MAIN");

    }//GEN-LAST:event_menuViewDownloaderActionPerformed

    private void menuViewLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewLibraryActionPerformed
        // TODO add your handling code here:
        showCard("LIBRARY");
    }//GEN-LAST:event_menuViewLibraryActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
            // Esborrem el token en memòria
   this.authToken = null;

    // aturam el component de polling i li llevam el token
    pollingComponent.setRunning(false);
    pollingComponent.setToken(null);

    // esborram usuari recordat
    RememberHelper.clear();

    // desactivam menús i tornam al login
    setLoggedIn(false);
    showCard("LOGIN");
    }//GEN-LAST:event_menuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
        public void showCard(String name) {
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, name);
    }
        

    // 🔹 Cridarem això per activar/desactivar menús
    public void setLoggedIn(boolean loggedIn) {
        menuViewDownloader.setEnabled( loggedIn );
        menuViewLibrary.setEnabled( loggedIn );
        menuPreferences.setEnabled( loggedIn );
        menuLogout.setEnabled(loggedIn);
    }

    // 🔹 Quan el login tingui èxit, guardarem el token aquí
public void onLoginSuccess(String token) {
    // guardar el token a MainFrame
    this.authToken = token;

    // 🔹 donar el token al component i arrencar el polling
    pollingComponent.setToken(token);
    pollingComponent.setRunning(true);

    // activar menús i anar al panell principal
    setLoggedIn(true);
    showCard("MAIN");
}



    public String getAuthToken() {
        return authToken;
    }

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenu View;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPreferences;
    private javax.swing.JMenuItem menuViewDownloader;
    private javax.swing.JMenuItem menuViewLibrary;
    // End of variables declaration//GEN-END:variables
}

