/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gelabert.ytdlgui;

/**
 *
 * @author JGR
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnDownload = new javax.swing.JButton();
        chkAudioOnly = new javax.swing.JCheckBox();
        chkOpenPlayer = new javax.swing.JCheckBox();
        rbMp4 = new javax.swing.JRadioButton();
        rbMp3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabelFormat = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 300));

        jLabel1.setText("URL:");

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        chkAudioOnly.setText("Audio only");

        chkOpenPlayer.setText("Open player after download");

        buttonGroup1.add(rbMp4);
        rbMp4.setText("MP4");

        buttonGroup1.add(rbMp3);
        rbMp3.setText("MP3");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setLineWrap(true);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        jLabelFormat.setText("Format:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 19, Short.MAX_VALUE)
                        .addComponent(btnDownload)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFormat)
                                .addGap(18, 18, 18)
                                .addComponent(rbMp3)
                                .addGap(18, 18, 18)
                                .addComponent(rbMp4)
                                .addGap(18, 18, 18)
                                .addComponent(chkAudioOnly))
                            .addComponent(chkOpenPlayer))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownload))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMp3)
                    .addComponent(rbMp4)
                    .addComponent(chkAudioOnly)
                    .addComponent(jLabelFormat))
                .addGap(18, 18, 18)
                .addComponent(chkOpenPlayer)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
         String url = txtUrl.getText().trim();
    if (url.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Introdueix una URL.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    String format = rbMp3.isSelected() ? "mp3" : "mp4";

    txtLog.append("Simulant descàrrega de: " + url + "\n");
    txtLog.append("Format seleccionat: " + format + "\n\n");
    }//GEN-LAST:event_btnDownloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkAudioOnly;
    private javax.swing.JCheckBox chkOpenPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbMp3;
    private javax.swing.JRadioButton rbMp4;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
