/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gelabert.ytdlgui;

/**
 *
 * @author JGR
 */
public class PreferencesPanel extends javax.swing.JPanel {

     private MainFrame mainFrame;
    /**
     * Creates new form PreferencesPanel
     */
    public PreferencesPanel() {
        initComponents();
        txtSpeed.setEnabled(false);

    }
    
    public PreferencesPanel(MainFrame mainFrame) {
    this();
    this.mainFrame = mainFrame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTempFolder = new javax.swing.JLabel();
        btnBrowseTemp = new javax.swing.JButton();
        chkM3u = new javax.swing.JCheckBox();
        chkLimitSpeed = new javax.swing.JCheckBox();
        txtSpeed = new javax.swing.JLabel();
        txtYtdlpPath = new javax.swing.JLabel();
        btnBrowseYtdlp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jTextFieldtempfolder = new javax.swing.JTextField();
        lblFfmpeg = new javax.swing.JLabel();
        txtFfmpegPath = new javax.swing.JTextField();
        btnBrowseFfmpeg = new javax.swing.JButton();
        txtDownloadFolder = new javax.swing.JTextField();
        txtSpeedField = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 300));

        txtTempFolder.setText("Temporal Folder:");

        btnBrowseTemp.setText("Browse…");
        btnBrowseTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseTempActionPerformed(evt);
            }
        });

        chkM3u.setText("Create .m3u file");

        chkLimitSpeed.setText("Limit speed to:");
        chkLimitSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLimitSpeedActionPerformed(evt);
            }
        });

        txtSpeed.setText("KB/s");

        txtYtdlpPath.setText("Downloads:");

        btnBrowseYtdlp.setText("Browse…");
        btnBrowseYtdlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseYtdlpActionPerformed(evt);
            }
        });

        btnBack.setText("Back to main");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFfmpeg.setText("ffmpeg:");

        btnBrowseFfmpeg.setText("Browse...");
        btnBrowseFfmpeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseFfmpegActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTempFolder)
                                    .addComponent(lblFfmpeg)
                                    .addComponent(txtYtdlpPath))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldtempfolder)
                                    .addComponent(txtFfmpegPath)
                                    .addComponent(txtDownloadFolder)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkM3u)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkLimitSpeed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSpeed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBrowseTemp)
                            .addComponent(btnBrowseFfmpeg)
                            .addComponent(btnBrowseYtdlp))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempFolder)
                    .addComponent(btnBrowseTemp)
                    .addComponent(jTextFieldtempfolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFfmpeg)
                    .addComponent(txtFfmpegPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseFfmpeg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYtdlpPath)
                    .addComponent(txtDownloadFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseYtdlp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLimitSpeed)
                    .addComponent(txtSpeed)
                    .addComponent(txtSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkM3u)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseTempActionPerformed
         javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
    int result = chooser.showOpenDialog(this);
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File dir = chooser.getSelectedFile();
        txtTempFolder.setText(dir.getAbsolutePath());
    }
    }//GEN-LAST:event_btnBrowseTempActionPerformed

    private void btnBrowseYtdlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseYtdlpActionPerformed
    javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
    int result = chooser.showOpenDialog(this);
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File dir = chooser.getSelectedFile();
        txtTempFolder.setText(dir.getAbsolutePath());
    }
    }//GEN-LAST:event_btnBrowseYtdlpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            if (mainFrame != null) {
        mainFrame.showCard("MAIN");
    }//GEN-LAST:event_btnBackActionPerformed
    }        
    private void btnBrowseFfmpegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseFfmpegActionPerformed
        // TODO add your handling code here:
            javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
    int result = chooser.showOpenDialog(this);
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File file = chooser.getSelectedFile();
        txtFfmpegPath.setText(file.getAbsolutePath());
    
    }//GEN-LAST:event_btnBrowseFfmpegActionPerformed
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            javax.swing.JOptionPane.showMessageDialog(
        this,
        "Preferences saved (simulation).",
        "Information",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chkLimitSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLimitSpeedActionPerformed
        // TODO add your handling code here:
        txtSpeed.setEnabled(chkLimitSpeed.isSelected());
    }//GEN-LAST:event_chkLimitSpeedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrowseFfmpeg;
    private javax.swing.JButton btnBrowseTemp;
    private javax.swing.JButton btnBrowseYtdlp;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkLimitSpeed;
    private javax.swing.JCheckBox chkM3u;
    private javax.swing.JTextField jTextFieldtempfolder;
    private javax.swing.JLabel lblFfmpeg;
    private javax.swing.JTextField txtDownloadFolder;
    private javax.swing.JTextField txtFfmpegPath;
    private javax.swing.JLabel txtSpeed;
    private javax.swing.JTextField txtSpeedField;
    private javax.swing.JLabel txtTempFolder;
    private javax.swing.JLabel txtYtdlpPath;
    // End of variables declaration//GEN-END:variables
}
